-- ==============================================================================
-- 🛒 ACTUALIZACIÓN COMPLETA DE PRECIOS REALISTAS CON CENTRAL DE ABASTO
-- Supermercados: 1: Walmart | 2: Soriana | 3: La Comer | 4: Central de Abasto
-- ==============================================================================

-- 1. Asegurar Central de Abasto en la tabla 'supermercados'
INSERT INTO public.supermercados (id_supermercado, nombre) VALUES (4, 'Central de Abasto')
ON CONFLICT (id_supermercado) DO UPDATE SET nombre = 'Central de Abasto';

-- 2. Limpiar registros previos de Central de Abasto si existen
DELETE FROM public.precios_supermercado WHERE id_supermercado = 4;

-- 3. Actualizar precios de Walmart (1), Soriana (2), La Comer (3) e insertar Central de Abasto (4)
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 3 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 3 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 3 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (3, 4, 24.48);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 4 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 4 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 4 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (4, 4, 11.52);
UPDATE public.precios_supermercado SET precio = 98.00 WHERE id_ingrediente = 5 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 93.10 WHERE id_ingrediente = 5 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 103.88 WHERE id_ingrediente = 5 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (5, 4, 86.24);
UPDATE public.precios_supermercado SET precio = 124.00 WHERE id_ingrediente = 6 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 117.80 WHERE id_ingrediente = 6 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 131.44 WHERE id_ingrediente = 6 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (6, 4, 105.40);
UPDATE public.precios_supermercado SET precio = 10.00 WHERE id_ingrediente = 9 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 9.50 WHERE id_ingrediente = 9 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 10.60 WHERE id_ingrediente = 9 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (9, 4, 7.20);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 11 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 11 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 11 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (11, 4, 12.96);
UPDATE public.precios_supermercado SET precio = 26.00 WHERE id_ingrediente = 12 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 24.70 WHERE id_ingrediente = 12 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 27.56 WHERE id_ingrediente = 12 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (12, 4, 17.50);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 13 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 13 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 13 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (13, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 14 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 14 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 14 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (14, 4, 17.28);
UPDATE public.precios_supermercado SET precio = 35.00 WHERE id_ingrediente = 18 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 33.25 WHERE id_ingrediente = 18 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 37.10 WHERE id_ingrediente = 18 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (18, 4, 25.20);
UPDATE public.precios_supermercado SET precio = 29.00 WHERE id_ingrediente = 24 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 27.55 WHERE id_ingrediente = 24 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 30.74 WHERE id_ingrediente = 24 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (24, 4, 20.88);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 29 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 29 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 29 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (29, 4, 17.28);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 34 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 34 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 34 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (34, 4, 12.96);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 35 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 35 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 35 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (35, 4, 34.44);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 37 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 37 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 37 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (37, 4, 36.96);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 47 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 47 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 47 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (47, 4, 57.50);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 50 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 50 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 50 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (50, 4, 199.75);
UPDATE public.precios_supermercado SET precio = 54.00 WHERE id_ingrediente = 54 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 51.30 WHERE id_ingrediente = 54 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 57.24 WHERE id_ingrediente = 54 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (54, 4, 44.28);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 55 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 55 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 55 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (55, 4, 17.50);
UPDATE public.precios_supermercado SET precio = 27.00 WHERE id_ingrediente = 56 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 25.65 WHERE id_ingrediente = 56 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 28.62 WHERE id_ingrediente = 56 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (56, 4, 22.14);
UPDATE public.precios_supermercado SET precio = 39.00 WHERE id_ingrediente = 57 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 37.05 WHERE id_ingrediente = 57 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 41.34 WHERE id_ingrediente = 57 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (57, 4, 34.32);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 58 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 58 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 58 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (58, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 26.00 WHERE id_ingrediente = 59 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 24.70 WHERE id_ingrediente = 59 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 27.56 WHERE id_ingrediente = 59 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (59, 4, 22.88);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 60 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 60 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 60 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (60, 4, 27.88);
UPDATE public.precios_supermercado SET precio = 19.50 WHERE id_ingrediente = 61 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 18.52 WHERE id_ingrediente = 61 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 20.67 WHERE id_ingrediente = 61 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (61, 4, 17.16);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 62 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 62 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 62 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (62, 4, 47.56);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 63 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 63 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 63 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (63, 4, 11.90);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 64 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 64 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 64 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (64, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 65 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 65 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 65 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (65, 4, 223.88);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 66 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 66 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 66 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (66, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 67 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 67 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 67 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (67, 4, 33.44);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 68 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 68 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 68 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (68, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 45.00 WHERE id_ingrediente = 69 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 42.75 WHERE id_ingrediente = 69 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 47.70 WHERE id_ingrediente = 69 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (69, 4, 39.60);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 70 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 70 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 70 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (70, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 71 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 71 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 71 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (71, 4, 28.90);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 72 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 72 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 72 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (72, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 62.00 WHERE id_ingrediente = 73 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 58.90 WHERE id_ingrediente = 73 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 65.72 WHERE id_ingrediente = 73 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (73, 4, 39.90);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 74 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 74 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 74 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (74, 4, 51.04);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 75 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 75 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 75 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (75, 4, 29.92);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 76 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 76 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 76 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (76, 4, 74.75);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 77 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 77 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 77 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (77, 4, 56.02);
UPDATE public.precios_supermercado SET precio = 46.00 WHERE id_ingrediente = 78 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 43.70 WHERE id_ingrediente = 78 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 48.76 WHERE id_ingrediente = 78 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (78, 4, 37.72);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 79 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 79 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 79 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (79, 4, 14.08);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 80 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 80 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 80 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (80, 4, 14.08);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 81 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 81 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 81 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (81, 4, 29.52);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 82 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 82 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 82 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (82, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 83 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 83 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 83 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (83, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 10.00 WHERE id_ingrediente = 84 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 9.50 WHERE id_ingrediente = 84 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 10.60 WHERE id_ingrediente = 84 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (84, 4, 8.80);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 85 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 85 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 85 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (85, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 65.00 WHERE id_ingrediente = 86 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 61.75 WHERE id_ingrediente = 86 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 68.90 WHERE id_ingrediente = 86 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (86, 4, 62.47);
UPDATE public.precios_supermercado SET precio = 54.00 WHERE id_ingrediente = 87 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 51.30 WHERE id_ingrediente = 87 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 57.24 WHERE id_ingrediente = 87 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (87, 4, 44.28);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 88 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 88 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 88 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (88, 4, 14.08);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 89 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 89 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 89 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (89, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 26.00 WHERE id_ingrediente = 90 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 24.70 WHERE id_ingrediente = 90 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 27.56 WHERE id_ingrediente = 90 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (90, 4, 22.88);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 91 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 91 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 91 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (91, 4, 18.00);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 92 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 92 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 92 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (92, 4, 22.96);
UPDATE public.precios_supermercado SET precio = 85.00 WHERE id_ingrediente = 93 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 80.75 WHERE id_ingrediente = 93 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 90.10 WHERE id_ingrediente = 93 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (93, 4, 69.70);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 94 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 94 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 94 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (94, 4, 16.80);
UPDATE public.precios_supermercado SET precio = 52.00 WHERE id_ingrediente = 95 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 49.40 WHERE id_ingrediente = 95 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 55.12 WHERE id_ingrediente = 95 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (95, 4, 45.76);
UPDATE public.precios_supermercado SET precio = 15.00 WHERE id_ingrediente = 96 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 14.25 WHERE id_ingrediente = 96 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 15.90 WHERE id_ingrediente = 96 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (96, 4, 38.75);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 97 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 97 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 97 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (97, 4, 31.16);
UPDATE public.precios_supermercado SET precio = 15.00 WHERE id_ingrediente = 98 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 14.25 WHERE id_ingrediente = 98 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 15.90 WHERE id_ingrediente = 98 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (98, 4, 13.20);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 99 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 99 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 99 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (99, 4, 167.25);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 100 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 100 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 100 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (100, 4, 14.08);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 101 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 101 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 101 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (101, 4, 31.68);
UPDATE public.precios_supermercado SET precio = 52.00 WHERE id_ingrediente = 102 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 49.40 WHERE id_ingrediente = 102 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 55.12 WHERE id_ingrediente = 102 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (102, 4, 32.20);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 103 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 103 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 103 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (103, 4, 29.92);
UPDATE public.precios_supermercado SET precio = 10.00 WHERE id_ingrediente = 104 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 9.50 WHERE id_ingrediente = 104 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 10.60 WHERE id_ingrediente = 104 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (104, 4, 8.80);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 105 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 105 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 105 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (105, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 106 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 106 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 106 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (106, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 107 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 107 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 107 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (107, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 108 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 108 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 108 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (108, 4, 190.75);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 109 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 109 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 109 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (109, 4, 42.24);
UPDATE public.precios_supermercado SET precio = 12.00 WHERE id_ingrediente = 110 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 11.40 WHERE id_ingrediente = 110 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 12.72 WHERE id_ingrediente = 110 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (110, 4, 10.56);
UPDATE public.precios_supermercado SET precio = 85.00 WHERE id_ingrediente = 111 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 80.75 WHERE id_ingrediente = 111 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 90.10 WHERE id_ingrediente = 111 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (111, 4, 63.00);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 112 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 112 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 112 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (112, 4, 100.00);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 113 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 113 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 113 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (113, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 114 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 114 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 114 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (114, 4, 39.36);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 115 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 115 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 115 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (115, 4, 29.92);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 116 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 116 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 116 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (116, 4, 42.24);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 117 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 117 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 117 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (117, 4, 39.20);
UPDATE public.precios_supermercado SET precio = 78.00 WHERE id_ingrediente = 118 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 74.10 WHERE id_ingrediente = 118 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 82.68 WHERE id_ingrediente = 118 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (118, 4, 63.96);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 119 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 119 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 119 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (119, 4, 79.50);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 120 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 120 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 120 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (120, 4, 13.12);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 121 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 121 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 121 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (121, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 122 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 122 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 122 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (122, 4, 42.24);
UPDATE public.precios_supermercado SET precio = 15.00 WHERE id_ingrediente = 123 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 14.25 WHERE id_ingrediente = 123 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 15.90 WHERE id_ingrediente = 123 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (123, 4, 12.30);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 124 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 124 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 124 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (124, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 185.00 WHERE id_ingrediente = 125 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 175.75 WHERE id_ingrediente = 125 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 196.10 WHERE id_ingrediente = 125 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (125, 4, 143.00);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 126 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 126 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 126 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (126, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 127 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 127 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 127 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (127, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 128 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 128 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 128 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (128, 4, 31.16);
UPDATE public.precios_supermercado SET precio = 16.00 WHERE id_ingrediente = 129 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.20 WHERE id_ingrediente = 129 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 16.96 WHERE id_ingrediente = 129 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (129, 4, 13.12);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 130 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 130 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 130 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (130, 4, 397.50);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 131 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 131 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 131 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (131, 4, 31.16);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 132 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 132 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 132 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (132, 4, 39.36);
UPDATE public.precios_supermercado SET precio = 39.00 WHERE id_ingrediente = 133 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 37.05 WHERE id_ingrediente = 133 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 41.34 WHERE id_ingrediente = 133 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (133, 4, 34.32);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 134 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 134 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 134 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (134, 4, 36.96);
UPDATE public.precios_supermercado SET precio = 29.00 WHERE id_ingrediente = 135 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 27.55 WHERE id_ingrediente = 135 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 30.74 WHERE id_ingrediente = 135 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (135, 4, 25.52);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 136 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 136 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 136 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (136, 4, 33.44);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 137 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 137 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 137 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (137, 4, 249.75);
UPDATE public.precios_supermercado SET precio = 14.00 WHERE id_ingrediente = 138 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 13.30 WHERE id_ingrediente = 138 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 14.84 WHERE id_ingrediente = 138 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (138, 4, 12.32);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 139 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 139 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 139 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (139, 4, 42.24);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 140 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 140 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 140 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (140, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 52.00 WHERE id_ingrediente = 141 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 49.40 WHERE id_ingrediente = 141 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 55.12 WHERE id_ingrediente = 141 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (141, 4, 45.76);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 142 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 142 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 142 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (142, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 143 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 143 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 143 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (143, 4, 25.00);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 144 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 144 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 144 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (144, 4, 27.88);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 145 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 145 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 145 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (145, 4, 36.96);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 146 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 146 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 146 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (146, 4, 190.75);
UPDATE public.precios_supermercado SET precio = 29.00 WHERE id_ingrediente = 147 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 27.55 WHERE id_ingrediente = 147 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 30.74 WHERE id_ingrediente = 147 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (147, 4, 25.52);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 148 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 148 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 148 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (148, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 58.00 WHERE id_ingrediente = 149 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 55.10 WHERE id_ingrediente = 149 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 61.48 WHERE id_ingrediente = 149 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (149, 4, 51.04);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 150 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 150 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 150 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (150, 4, 36.96);
UPDATE public.precios_supermercado SET precio = 26.00 WHERE id_ingrediente = 151 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 24.70 WHERE id_ingrediente = 151 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 27.56 WHERE id_ingrediente = 151 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (151, 4, 22.88);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 152 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 152 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 152 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (152, 4, 28.16);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 153 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 153 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 153 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (153, 4, 39.36);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 154 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 154 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 154 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (154, 4, 22.96);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 155 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 155 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 155 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (155, 4, 11.90);
UPDATE public.precios_supermercado SET precio = 34.00 WHERE id_ingrediente = 156 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 32.30 WHERE id_ingrediente = 156 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 36.04 WHERE id_ingrediente = 156 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (156, 4, 29.92);
UPDATE public.precios_supermercado SET precio = 98.00 WHERE id_ingrediente = 157 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 93.10 WHERE id_ingrediente = 157 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 103.88 WHERE id_ingrediente = 157 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (157, 4, 86.24);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 158 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 158 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 158 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (158, 4, 28.16);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 159 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 159 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 159 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (159, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 135.00 WHERE id_ingrediente = 160 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 128.25 WHERE id_ingrediente = 160 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 143.10 WHERE id_ingrediente = 160 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (160, 4, 110.70);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 161 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 161 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 161 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (161, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 162 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 162 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 162 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (162, 4, 28.16);
UPDATE public.precios_supermercado SET precio = 36.00 WHERE id_ingrediente = 163 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 34.20 WHERE id_ingrediente = 163 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 38.16 WHERE id_ingrediente = 163 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (163, 4, 28.90);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 164 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 164 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 164 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (164, 4, 57.50);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 165 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 165 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 165 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (165, 4, 42.24);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 166 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 166 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 166 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (166, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 28.00 WHERE id_ingrediente = 167 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 26.60 WHERE id_ingrediente = 167 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 29.68 WHERE id_ingrediente = 167 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (167, 4, 24.64);
UPDATE public.precios_supermercado SET precio = 32.00 WHERE id_ingrediente = 168 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 30.40 WHERE id_ingrediente = 168 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 33.92 WHERE id_ingrediente = 168 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (168, 4, 65.00);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 169 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 169 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 169 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (169, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 15.00 WHERE id_ingrediente = 170 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 14.25 WHERE id_ingrediente = 170 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 15.90 WHERE id_ingrediente = 170 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (170, 4, 11.20);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 171 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 171 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 171 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (171, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 172 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 172 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 172 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (172, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 24.00 WHERE id_ingrediente = 173 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 22.80 WHERE id_ingrediente = 173 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 25.44 WHERE id_ingrediente = 173 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (173, 4, 21.12);
UPDATE public.precios_supermercado SET precio = 42.00 WHERE id_ingrediente = 174 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 39.90 WHERE id_ingrediente = 174 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 44.52 WHERE id_ingrediente = 174 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (174, 4, 36.96);
UPDATE public.precios_supermercado SET precio = 21.50 WHERE id_ingrediente = 175 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.43 WHERE id_ingrediente = 175 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 22.79 WHERE id_ingrediente = 175 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (175, 4, 18.92);
UPDATE public.precios_supermercado SET precio = 52.00 WHERE id_ingrediente = 190 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 49.40 WHERE id_ingrediente = 190 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 55.12 WHERE id_ingrediente = 190 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (190, 4, 32.00);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 192 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 192 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 192 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (192, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 16.50 WHERE id_ingrediente = 193 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 15.67 WHERE id_ingrediente = 193 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 17.49 WHERE id_ingrediente = 193 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (193, 4, 14.52);
UPDATE public.precios_supermercado SET precio = 12.00 WHERE id_ingrediente = 196 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 11.40 WHERE id_ingrediente = 196 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 12.72 WHERE id_ingrediente = 196 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (196, 4, 10.56);
UPDATE public.precios_supermercado SET precio = 48.00 WHERE id_ingrediente = 202 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 45.60 WHERE id_ingrediente = 202 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 50.88 WHERE id_ingrediente = 202 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (202, 4, 39.36);
UPDATE public.precios_supermercado SET precio = 22.00 WHERE id_ingrediente = 204 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 20.90 WHERE id_ingrediente = 204 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 23.32 WHERE id_ingrediente = 204 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (204, 4, 19.36);
UPDATE public.precios_supermercado SET precio = 18.00 WHERE id_ingrediente = 208 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 17.10 WHERE id_ingrediente = 208 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 19.08 WHERE id_ingrediente = 208 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (208, 4, 15.84);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 223 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 223 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 223 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (223, 4, 25.00);
UPDATE public.precios_supermercado SET precio = 38.00 WHERE id_ingrediente = 225 AND id_supermercado = 1;
UPDATE public.precios_supermercado SET precio = 36.10 WHERE id_ingrediente = 225 AND id_supermercado = 2;
UPDATE public.precios_supermercado SET precio = 40.28 WHERE id_ingrediente = 225 AND id_supermercado = 3;
INSERT INTO public.precios_supermercado (id_ingrediente, id_supermercado, precio) VALUES (225, 4, 33.44);